'use client';

import { useEffect, useState } from 'react';
import { useRouter } from 'next/navigation';
import { ProtectedRoute } from '@/components/auth/protected-route';
import { ProjectCard } from '@/components/dashboard/project-card';
import { useAuth } from '@/lib/auth/auth-context';
import { api } from '@/lib/api-client';
import type { Project } from '@/types/project';

function DashboardContent() { const { user, logout } = useAuth(); const router = useRouter(); const [projects, setProjects] = useState<Project[]>([]); const [error, setError] = useState(''); const [showForm, setShowForm] = useState(false); const [pending, setPending] = useState(false); useEffect(() => { api.projects().then(setProjects).catch((e) => setError(e.message)); }, []); async function createProject(event: React.FormEvent<HTMLFormElement>) { event.preventDefault(); setPending(true); const data = Object.fromEntries(new FormData(event.currentTarget)); try { const project = await api.createProject({ name: String(data.name), description: String(data.description) }); router.push(`/projects/${project.id}`); } catch (e) { setError(e instanceof Error ? e.message : 'Unable to create project'); } finally { setPending(false); } } return <main className="min-h-screen bg-[#07101d]"><header className="border-b border-slate-800 bg-slate-950/80"><div className="mx-auto flex max-w-6xl items-center justify-between px-6 py-5"><div><p className="font-mono text-xs tracking-[.3em] text-cyan-400">ISOMORF / CONTROL ROOM</p><h1 className="mt-2 text-xl font-semibold text-white">Structural workspace</h1></div><button onClick={() => logout().then(() => router.replace('/login'))} className="text-sm text-slate-400 hover:text-white">Sign out</button></div></header><section className="mx-auto max-w-6xl px-6 py-12"><div className="flex flex-col justify-between gap-5 sm:flex-row sm:items-end"><div><p className="text-sm text-slate-500">Good to see you,</p><h2 className="mt-1 text-4xl font-semibold text-white">{user?.first_name}</h2></div><button onClick={() => setShowForm(true)} className="rounded-lg bg-cyan-400 px-5 py-3 font-semibold text-slate-950">+ New project</button></div>{error && <p className="mt-6 rounded-lg bg-red-500/10 p-3 text-sm text-red-300">{error}</p>}<div className="mt-12 grid gap-4 md:grid-cols-2 lg:grid-cols-3">{projects.map((project) => <ProjectCard key={project.id} project={project} />)}{projects.length === 0 && <div className="rounded-xl border border-dashed border-slate-700 p-10 text-slate-500">No projects yet. Create your first structural workspace.</div>}</div></section>{showForm && <div className="fixed inset-0 grid place-items-center bg-slate-950/80 p-6"><form onSubmit={createProject} className="w-full max-w-md rounded-xl border border-slate-700 bg-slate-900 p-6"><h3 className="text-xl font-semibold text-white">New project</h3><input required name="name" placeholder="Project name" className="field mt-5" /><textarea name="description" placeholder="Description" className="field mt-3 min-h-28" /><div className="mt-5 flex justify-end gap-3"><button type="button" onClick={() => setShowForm(false)} className="px-4 py-2 text-slate-400">Cancel</button><button disabled={pending} className="rounded-lg bg-cyan-400 px-4 py-2 font-semibold text-slate-950">Create</button></div></form></div>}</main>; }
export default function DashboardPage() { return <ProtectedRoute><DashboardContent /></ProtectedRoute>; }
